Changement de titre
ClubCedille/clubcedille.github.io pull request #81
Opened 2021-11-02 15:51 UTC by ThomasCardin

2021-11-02 16:10 UTC, cguertin14 commented
Merci pour la PR. Je vais changer mon titre plus tard ajd.

2021-11-02 19:44 UTC, AXDOOMER commented
Avec vous des photos professionnelles que vous pouvez mettre sur le site pour les membres de l'exec? Ça permet aux étudiants de l'ÉTS de vous reconnaître une fois qu'ils ont vu notre site.

2021-11-05 23:09 UTC, notarock commented on _data/fr/members.yml
> +      - title: linkedin
Si tu ne met pas de liens ici, je crois que ça serait mieux d'enlevé l'entrée.
Sinon, ça rajoute des liens en dessous de ton "profile" mais ils sont innutiles...

<img width="265" alt="image" src="https://user-images.githubusercontent.com/25652765/140587829-316e1cb2-2f0c-45de-a419-c9e7a8df1936.png">

Si tu enlève "title" et "url" ça ne devrait plus apparaitre

2021-11-08 20:24 UTC, notarock requested changes
Voir commentaire(s)

2021-11-12 22:12 UTC, notarock commented
@ThomasCardin

2021-11-12 22:25 UTC, notarock approved these changes
LGTM!

2021-11-12 22:35 UTC, ThomasCardin commented
@cguertin14 Je n'ai pas changé ton titre encore. Je sais qu'on avait parlé de te mettre chef d'équipe pour les futurs projets à venir. Je te laisse l'honneur de faire les changements nécessaires 😃

2021-11-12 22:36 UTC, cguertin14 commented
> @cguertin14 Je n'ai pas changé ton titre encore. Je sais qu'on avait parlé de te mettre chef d'équipe pour les futurs projets à venir. Je te laisse l'honneur de faire les changements nécessaires 😃

pas de soucis, je vais faire ça dans une autre PR 👍🏻

2021-11-13 00:31 UTC, merged